# 1. Introducción

**¿Qué es el proceso ETL?**
ETL son las siglas en inglés de Extract, Transform, Load (Extraer, Transformar y Cargar). Es un proceso fundamental en ingeniería de datos que permite mover datos desde múltiples fuentes, limpiarlos, formatearlos y cargarlos en un sistema de almacenamiento final para su posterior análisis o uso en modelos predictivos.

**Objetivo de la limpieza de datos**
El objetivo principal es identificar y corregir errores, inconsistencias, valores nulos o duplicados en el conjunto de datos. Esto asegura que la información sea confiable, precisa y útil para la toma de decisiones.

**Importancia de la calidad de los datos para análisis y Machine Learning**
La calidad de los datos es crucial. Como dice el adagio en ciencia de datos: "Garbage In, Garbage Out" (Basura entra, basura sale). Modelos de Machine Learning entrenados con datos de mala calidad producirán predicciones erróneas o sesgadas, sin importar cuán sofisticado sea el algoritmo. Un buen preprocesamiento garantiza resultados robustos y confiables.

--- 
## 2. Importación de librerías

A continuación, importamos las herramientas necesarias para nuestro análisis:

*   **`pandas`**: Es la librería principal para manipulación y análisis de datos en Python. Nos permite trabajar con estructuras de datos como DataFrames.
*   **`numpy`**: Proporciona soporte para arreglos y matrices multidimensionales, además de funciones matemáticas de alto nivel para operar con estos arreglos.
*   **`pathlib.Path`**: Ofrece clases que representan rutas del sistema de archivos con semántica apropiada para distintos sistemas operativos, facilitando la gestión de rutas a archivos.

In [66]:
import pandas as pd
import numpy as np
from pathlib import Path

---
## 3. Carga del dataset (Extract)

En esta etapa, extraemos los datos de nuestra fuente. Procedemos a cargar el dataset desde la carpeta `dataset/`. Es importante definir la ruta correctamente y utilizar pandas para leer el archivo CSV. Luego, mostraremos la cantidad de filas y columnas, y un vistazo a los primeros registros para entender su estructura básica.

In [67]:
# Definimos la ruta al archivo del dataset.
# Asegúrate de que el archivo correcto se encuentre en esta ruta (puede variar según el nombre del archivo exacto)
file_path = Path("../dataset/Inventario_Departamental_Gases_Efecto_Invernadero_20260529.csv")

# Verificamos si el archivo existe antes de cargarlo
if file_path.exists():
    df = pd.read_csv(file_path)
    print(f"El dataset tiene {df.shape[0]} filas y {df.shape[1]} columnas.\n")
    print("Primeros registros del dataset:")
    display(df.head())
else:
    print(f"El archivo no fue encontrado en la ruta: {file_path}")
    # Dataset de ejemplo para demostrar el notebook si no se encuentra el archivo
    print("Creando un dataset de ejemplo para la demostración...")
    data = {
        ' Nombre Departamento ' : ['Bogotá', 'Antioquia', 'Valle', 'Bogotá', 'Meta'],
        'CAP': [1, 2, 3, 1, 4],
        'CAT': ['A', 'B', 'C', 'A', 'D'],
        'SUBNROM': [10, 20, 30, 10, 40],
        'NUM': [100, 200, 300, 100, 400],
        'REPORTAR': ['SI', 'NO', 'SI', 'SI', 'NO'],
        'NIVEL': [1, 2, 1, 1, 3],
        'RUBRO': ['X', 'Y', 'Z', 'X', 'W'],
        'SECTORES': ['S1', 'S2', 'S3', 'S1', 'S4'],
        'Emisiones': [150.5, np.nan, 80.2, 150.5, np.nan]
    }
    df = pd.DataFrame(data)
    print(f"El dataset de ejemplo tiene {df.shape[0]} filas y {df.shape[1]} columnas.\n")
    print("Primeros registros del dataset:")
    display(df.head())

El dataset tiene 17226 filas y 52 columnas.

Primeros registros del dataset:

C:\Users\emanu\AppData\Local\Temp\ipykernel_13992\1289013501.py:7: DtypeWarning: Columns (33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,MOD,CAP,CAT,SUB,NROM,NUM,Departamento,Reportar,Nivel,Categorias,...,HFC-236faeq,HFC-245faeq,HFC-365mfceq,HFC-43-10meeeq,PFC-14eq,PFC-116eq,SF6eq,Abosorciones_totales,Emisiones_Totales,Emisiones_Netas
0,1.0,A,5.0,b,i,NaN,CAUCA,SI,1A5biSI,1A5bi - Móvil (componente aviación),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
1,2.0,A,NaN,NaN,NaN,NaN,CORDOBA,SI,2ASI,2A - Industria de los minerales,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2,1.0,C,1.0,a,NaN,NaN,GUAINIA,SI,1C1aSI,1C1a - Gasoductos,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
3,1.0,C,1.0,b,NaN,NaN,GUAINIA,SI,1C1bSI,1C1b - Embarcaciones,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
4,1.0,C,1.0,c,NaN,NaN,GUAINIA,SI,1C1cSI,1C1c - Otros,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0

---
## 4. Exploración inicial de los datos

Antes de transformar los datos, es vital comprender su naturaleza. En esta sección realizaremos un diagnóstico inicial para:

1.  **Dimensiones:** Confirmar cuántos datos tenemos (filas y columnas).
2.  **Columnas:** Conocer qué información almacena cada variable con sus respectivos nombres.
3.  **Tipos de datos:** Verificar si las variables son numéricas, texto, booleanas, etc.
4.  **Valores nulos:** Identificar la cantidad de datos faltantes por columna.
5.  **Estadísticas descriptivas:** Obtener un resumen matemático preliminar de las variables.

In [68]:
print("--- Dimensiones del dataset ---")
print(f"Filas: {df.shape[0]}, Columnas: {df.shape[1]}\n")

print("--- Nombres de columnas ---")
print(df.columns.tolist())
print("\n--- Tipos de datos ---")
print(df.dtypes)

print("\n--- Valores nulos por columna ---")
print(df.isnull().sum())

print("\n--- Estadísticas descriptivas ---")
display(df.describe(include='all'))

--- Dimensiones del dataset ---
Filas: 17226, Columnas: 52

--- Nombres de columnas ---
['MOD', 'CAP', 'CAT', 'SUB', 'NROM', 'NUM', 'Departamento', 'Reportar', 'Nivel', 'Categorias', 'Rubro', 'Sector (Gráfica sectorial)', 'Sector (Colores histograma)', 'CO2abs', 'CO2', 'CH4', 'N2O', 'HFC-23', 'HFC-32', 'HFC-125', 'HFC-134a', 'HFC-143a', 'HFC-152a', 'HFC-227ea', 'HFC-236fa', 'HFC-245fa', 'HFC-365mfc', 'HFC-43-10mee', 'PFC-14', 'PFC-116', 'SF6', 'CO2abseq', 'CO2eq', 'CH4eq', 'N2Oeq', 'HFC-23eq', 'HFC-32eq', 'HFC-125eq', 'HFC-134aeq', 'HFC-143aeq', 'HFC-152aeq', 'HFC-227eaeq', 'HFC-236faeq', 'HFC-245faeq', 'HFC-365mfceq', 'HFC-43-10meeeq', 'PFC-14eq', 'PFC-116eq', 'SF6eq', 'Abosorciones_totales', 'Emisiones_Totales', 'Emisiones_Netas']

--- Tipos de datos ---
MOD                            float64
CAP                             object
CAT                            float64
SUB                             object
NROM                            object
NUM                            float64
Departamento                    object
Reportar                        object
Nivel                           object
Categorias                      object
Rubro                           object
Sector (Gráfica sectorial)      object
Sector (Colores histograma)     object
CO2abs                          object
CO2                             object
CH4                            float64
N2O                            float64
HFC-23                         float64
HFC-32                         float64
HFC-125                        float64
HFC-134a                       float64
HFC-143a                       float64
HFC-152a                       float64
HFC-227ea                      float64
HFC-236fa                      float64
HFC-245fa                      float64
HFC-365mfc                     float64
HFC-43-10mee                   float64
PFC-14                         float64
PFC-116                        float64
SF6                            float64
CO2abseq                        object
CO2eq                           object
CH4eq                           object
N2Oeq                           object
HFC-23eq                       float64
HFC-32eq                       float64
HFC-125eq                      float64
HFC-134aeq                     float64
HFC-143aeq                     float64
HFC-152aeq                     float64
HFC-227eaeq                    float64
HFC-236faeq                    float64
HFC-245faeq                    float64
HFC-365mfceq                   float64
HFC-43-10meeeq                 float64
PFC-14eq                       float64
PFC-116eq                      float64
SF6eq                          float64
Abosorciones_totales            object
Emisiones_Totales               object
Emisiones_Netas                 object
dtype: object

--- Valores nulos por columna ---
MOD                               33
CAP                              165
CAT                              792
SUB                             3366
NROM                            7524
NUM                            11649
Departamento                       0
Reportar                           0
Nivel                              0
Categorias                         0
Rubro                          13200
Sector (Gráfica sectorial)     13200
Sector (Colores histograma)    13200
CO2abs                         10127
CO2                             6742
CH4                             5234
N2O                             5686
HFC-23                          9999
HFC-32                          9933
HFC-125                         9801
HFC-134a                        9735
HFC-143a                        9900
HFC-152a                       10065
HFC-227ea                      10032
HFC-236fa                       9999
HFC-245fa                      10065
HFC-365mfc                     10032
HFC-43-10mee                   10164
PFC-14                          9999
PFC-116                         9999
SF6                            10032
CO2abseq                       10128
CO2eq                           6742
CH4eq                           5234
N2Oeq                           5685
HFC-23eq                        9999
HFC-32eq                        9933
HFC-125eq                       9801
HFC-134aeq                      9735
HFC-143aeq                      9900
HFC-152aeq                     10065
HFC-227eaeq                    10032
HFC-236faeq                     9999
HFC-245faeq                    10065
HFC-365mfceq                   10032
HFC-43-10meeeq                 10164
PFC-14eq                        9999
PFC-116eq                       9999
SF6eq                          10032
Abosorciones_totales           10128
Emisiones_Totales                 33
Emisiones_Netas                   33
dtype: int64

--- Estadísticas descriptivas ---

,MOD,CAP,CAT,SUB,NROM,NUM,Departamento,Reportar,Nivel,Categorias,...,HFC-236faeq,HFC-245faeq,HFC-365mfceq,HFC-43-10meeeq,PFC-14eq,PFC-116eq,SF6eq,Abosorciones_totales,Emisiones_Totales,Emisiones_Netas
count,17193.000000,17061,16434.000000,13860,9702,5577.000000,17226,17226,17226,17226,...,7227.000000,7161.000000,7194.000000,7062.0,7227.000000,7227.000000,7194.000000,7098,17193,17193
unique,NaN,8,NaN,13,11,NaN,33,1,521,380,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1016,6018,6792
top,NaN,B,NaN,b,i,NaN,CAUCA,SI,1A4ciiSI,Biomasa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0
freq,NaN,8712,NaN,5940,2178,NaN,522,17226,66,1584,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5687,10196,9357
mean,2.441459,NaN,2.985944,NaN,NaN,2.130178,NaN,NaN,NaN,NaN,...,0.000078,0.000026,0.004963,0.0,0.000052,0.000084,0.124404,NaN,NaN,NaN
std,0.872360,NaN,1.879400,NaN,NaN,1.029644,NaN,NaN,NaN,NaN,...,0.000939,0.000285,0.072522,0.0,0.000624,0.001005,1.975873,NaN,NaN,NaN
min,1.000000,NaN,1.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN
25%,2.000000,NaN,2.000000,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN
50%,3.000000,NaN,2.000000,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN
75%,3.000000,NaN,4.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN
max,4.000000,NaN,10.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,...,0.018043,0.007018,1.701400,0.0,0.011988,0.019305,64.068217,NaN,NaN,NaN

---
## 5. Transformación de los datos (Transform)

### Eliminación de columnas innecesarias

En el análisis de datos, mantener información irrelevante consume recursos y puede generar ruido en los modelos. Las columnas `CAP`, `CAT`, `SUBNROM`, `NUM`, `REPORTAR`, `NIVEL`, `RUBRO` y `SECTORES` son identificadas como variables administrativas o de clasificación interna que no aportan valor predictivo ni analítico para el objetivo general de evaluar las emisiones.

Por lo tanto, procederemos a eliminarlas.

In [69]:
# Lista de columnas que deseamos eliminar, exactamente como se solicita
columnas_a_eliminar = ['CAP', 'CAT', 'SUBNROM', 'NUM', 'Reportar', 'Nivel', 'Rubro', 'Sector (Gráfica sectorial)', 'Sector (Colores histograma)']

# Verificamos cuáles de estas columnas realmente existen en el dataset
columnas_existentes = [col for col in columnas_a_eliminar if col in df.columns]
columnas_no_encontradas = [col for col in columnas_a_eliminar if col not in df.columns]

print("--- Verificación de columnas a eliminar ---")
print(f"Columnas encontradas y que serán eliminadas: {columnas_existentes}")
if columnas_no_encontradas:
    print(f"Columnas NO encontradas en el dataset: {columnas_no_encontradas}")

# Eliminamos las columnas encontradas
df = df.drop(columns=columnas_existentes)
print("\nLas columnas han sido eliminadas.")

--- Verificación de columnas a eliminar ---
Columnas encontradas y que serán eliminadas: ['CAP', 'CAT', 'NUM', 'Reportar', 'Nivel', 'Rubro', 'Sector (Gráfica sectorial)', 'Sector (Colores histograma)']
Columnas NO encontradas en el dataset: ['SUBNROM']

Las columnas han sido eliminadas.

### Transformación de las variables MOD y Categorías

Durante la exploración inicial del conjunto de datos se identificó que la columna **categorias** contiene un nivel de detalle muy específico para cada fuente de emisión de gases de efecto invernadero.

Ejemplos:

- 1A5bi - Móvil (componente aviación)
- 1C1a - Gasoductos
- 1C1b - Embarcaciones
- 2A - Industria de los minerales
- 3A1 - Fermentación entérica

Aunque este nivel de detalle puede ser útil para análisis especializados, genera una gran cantidad de categorías y dificulta el análisis agregado por sector económico o ambiental.

---

##### Uso de la variable MOD

La variable **MOD** representa la clasificación principal de los sectores de emisión según la metodología del IPCC (Panel Intergubernamental sobre Cambio Climático).

La correspondencia es la siguiente:

| MOD | Sector Principal |
|------|----------------|
| 1 | Energía |
| 2 | Procesos Industriales |
| 3 | Agricultura |
| 4 | Silvicultura y Otros Usos del Suelo |
| 5 | Residuos |

---

#### Estrategia aplicada

Se creó una nueva variable denominada **sector_principal**, utilizando la información contenida en la columna **MOD**.

De esta manera, las categorías específicas quedan agrupadas dentro de uno de los cinco grandes sectores de emisión.

Por ejemplo:

| MOD | Categoría Original | Sector Principal |
|------|-------------------|------------------|
| 1 | 1A5bi - Móvil (componente aviación) | Energía |
| 1 | 1C1a - Gasoductos | Energía |
| 2 | 2A - Industria de los minerales | Procesos Industriales |
| 3 | 3A1 - Fermentación entérica | Agricultura |

---

#### Justificación

La creación de la variable **sector_principal** permite:

- Reducir la complejidad del conjunto de datos.
- Facilitar análisis exploratorios y visualizaciones.
- Realizar comparaciones entre grandes sectores económicos.
- Simplificar futuros modelos de Machine Learning.
- Mantener la información detallada de las categorías originales para análisis posteriores.

Por esta razón, se decidió conservar ambas variables:

- **sector_principal** → nivel agregado.
- **categorias** → nivel detallado.

Esta estrategia permite realizar análisis tanto generales como específicos sin perder información relevante.

In [70]:
# Diccionario de equivalencias
mapa_mod = {
    1: "Energía",
    2: "Procesos Industriales",
    3: "Agricultura",
    4: "Silvicultura y Otros Usos del Suelo",
    5: "Residuos"
}

df["sector_principal"] = df["MOD"].map(mapa_mod)

# Renombrar la categoría específica
df.rename(
    columns={"categorias": "subcategoria"},
    inplace=True
)

### Validación posterior

Verificamos que los cambios se hayan aplicado correctamente, revisando la nueva lista de columnas y las dimensiones del dataset.

In [71]:
print("--- Validación posterior a la eliminación ---")
print("Nuevas dimensiones del dataset:")
print(f"Filas: {df.shape[0]}, Columnas: {df.shape[1]}\n")
print("Columnas restantes:")
print(df.columns.tolist())

--- Validación posterior a la eliminación ---
Nuevas dimensiones del dataset:
Filas: 17226, Columnas: 45

Columnas restantes:
['MOD', 'SUB', 'NROM', 'Departamento', 'Categorias', 'CO2abs', 'CO2', 'CH4', 'N2O', 'HFC-23', 'HFC-32', 'HFC-125', 'HFC-134a', 'HFC-143a', 'HFC-152a', 'HFC-227ea', 'HFC-236fa', 'HFC-245fa', 'HFC-365mfc', 'HFC-43-10mee', 'PFC-14', 'PFC-116', 'SF6', 'CO2abseq', 'CO2eq', 'CH4eq', 'N2Oeq', 'HFC-23eq', 'HFC-32eq', 'HFC-125eq', 'HFC-134aeq', 'HFC-143aeq', 'HFC-152aeq', 'HFC-227eaeq', 'HFC-236faeq', 'HFC-245faeq', 'HFC-365mfceq', 'HFC-43-10meeeq', 'PFC-14eq', 'PFC-116eq', 'SF6eq', 'Abosorciones_totales', 'Emisiones_Totales', 'Emisiones_Netas', 'sector_principal']

---
## 6. Limpieza básica adicional

### Valores duplicados

Los registros duplicados pueden sesgar las métricas y los modelos al contar varias veces una misma observación. Vamos a detectar cuántos existen y eliminarlos de inmediato si los hay.

In [72]:
# Detectar duplicados
cantidad_duplicados = df.duplicated().sum()
print(f"Se encontraron {cantidad_duplicados} registros duplicados.")

if cantidad_duplicados > 0:
    # Eliminar duplicados
    df = df.drop_duplicates()
    print("Los registros duplicados han sido eliminados.")
else:
    print("No se requirió eliminación.")

Se encontraron 2089 registros duplicados.
Los registros duplicados han sido eliminados.

### Valores nulos

Identificamos la presencia de valores nulos (faltantes). En este momento **solo generaremos el diagnóstico y no realizaremos una imputación automática**. La imputación correcta se debe tomar basada en un análisis posterior con expertos de negocio.

**Posibles estrategias de tratamiento para el futuro:**
*   **Eliminación:** Si los nulos representan un porcentaje ínfimo (ej. < 5%), borrar la fila puede ser razonable.
*   **Imputación estadística:** Rellenar con la media, mediana o moda.
*   **Imputación por Machine Learning:** Predecir el valor usando variables relacionadas.
*   **Marcado explícito:** Indicar en una nueva columna que el valor fue nulo (ej. si los datos faltantes no son aleatorios).

In [73]:
print("--- Diagnóstico de valores nulos ---")

nulos_por_columna = df.isnull().sum()

print("Cantidad de valores nulos por columna:")
display(nulos_por_columna)

# Cantidad de registros antes de la limpieza
filas_antes = len(df)

# Eliminar registros donde MOD sea nulo
df = df.dropna(subset=['MOD'])

# Cantidad de registros eliminados
filas_despues = len(df)
eliminados = filas_antes - filas_despues

print(f"\nRegistros eliminados por tener MOD nulo: {eliminados}")
print(f"Registros restantes: {filas_despues}")

--- Diagnóstico de valores nulos ---
Cantidad de valores nulos por columna:

MOD                        33
SUB                      3366
NROM                     7524
Departamento                0
Categorias                  0
CO2abs                  10127
CO2                      6742
CH4                      5234
N2O                      5686
HFC-23                   9999
HFC-32                   9933
HFC-125                  9801
HFC-134a                 9735
HFC-143a                 9900
HFC-152a                10065
HFC-227ea               10032
HFC-236fa                9999
HFC-245fa               10065
HFC-365mfc              10032
HFC-43-10mee            10164
PFC-14                   9999
PFC-116                  9999
SF6                     10032
CO2abseq                10128
CO2eq                    6742
CH4eq                    5234
N2Oeq                    5685
HFC-23eq                 9999
HFC-32eq                 9933
HFC-125eq                9801
HFC-134aeq               9735
HFC-143aeq               9900
HFC-152aeq              10065
HFC-227eaeq             10032
HFC-236faeq              9999
HFC-245faeq             10065
HFC-365mfceq            10032
HFC-43-10meeeq          10164
PFC-14eq                 9999
PFC-116eq                9999
SF6eq                   10032
Abosorciones_totales    10128
Emisiones_Totales          33
Emisiones_Netas            33
sector_principal           33
dtype: int64

Registros eliminados por tener MOD nulo: 33
Registros restantes: 15104

### Estandarización de nombres de columnas

Tener nombres de columnas estandarizados facilita enormemente la programación y previene errores técnicos. Aplicaremos el siguiente formato a los encabezados:
1.  Convertir todas las letras a minúsculas.
2.  Quitar espacios en blanco al inicio o al final del nombre.
3.  Reemplazar los espacios intermedios por guiones bajos (`_`).

In [74]:
print("--- Estandarización de columnas ---")
print("Columnas originales:", df.columns.tolist())

# Aplicamos strip, lower y replace utilizando list comprehension
df.columns = [col.strip().lower().replace(' ', '_') for col in df.columns]

print("\nColumnas estandarizadas:", df.columns.tolist())

--- Estandarización de columnas ---
Columnas originales: ['MOD', 'SUB', 'NROM', 'Departamento', 'Categorias', 'CO2abs', 'CO2', 'CH4', 'N2O', 'HFC-23', 'HFC-32', 'HFC-125', 'HFC-134a', 'HFC-143a', 'HFC-152a', 'HFC-227ea', 'HFC-236fa', 'HFC-245fa', 'HFC-365mfc', 'HFC-43-10mee', 'PFC-14', 'PFC-116', 'SF6', 'CO2abseq', 'CO2eq', 'CH4eq', 'N2Oeq', 'HFC-23eq', 'HFC-32eq', 'HFC-125eq', 'HFC-134aeq', 'HFC-143aeq', 'HFC-152aeq', 'HFC-227eaeq', 'HFC-236faeq', 'HFC-245faeq', 'HFC-365mfceq', 'HFC-43-10meeeq', 'PFC-14eq', 'PFC-116eq', 'SF6eq', 'Abosorciones_totales', 'Emisiones_Totales', 'Emisiones_Netas', 'sector_principal']

Columnas estandarizadas: ['mod', 'sub', 'nrom', 'departamento', 'categorias', 'co2abs', 'co2', 'ch4', 'n2o', 'hfc-23', 'hfc-32', 'hfc-125', 'hfc-134a', 'hfc-143a', 'hfc-152a', 'hfc-227ea', 'hfc-236fa', 'hfc-245fa', 'hfc-365mfc', 'hfc-43-10mee', 'pfc-14', 'pfc-116', 'sf6', 'co2abseq', 'co2eq', 'ch4eq', 'n2oeq', 'hfc-23eq', 'hfc-32eq', 'hfc-125eq', 'hfc-134aeq', 'hfc-143aeq', 'hfc-152aeq', 'hfc-227eaeq', 'hfc-236faeq', 'hfc-245faeq', 'hfc-365mfceq', 'hfc-43-10meeeq', 'pfc-14eq', 'pfc-116eq', 'sf6eq', 'abosorciones_totales', 'emisiones_totales', 'emisiones_netas', 'sector_principal']

---
## 7. Verificación final

Antes de guardar el dataset y finalizar la etapa ETL, damos un último vistazo para asegurar que todas las transformaciones se aplicaron adecuadamente.

In [75]:
print("--- Estado final del Dataset ---")
print(f"Dimensiones finales: {df.shape[0]} filas, {df.shape[1]} columnas.\n")
print(f"Número total de registros: {df.shape[0]}")
print(f"Número total de columnas: {df.shape[1]}\n")

print("--- Tipos de datos finales ---")
print(df.dtypes)

print("\n--- Vista previa del dataset limpio ---")
display(df.head())

--- Estado final del Dataset ---
Dimensiones finales: 15104 filas, 45 columnas.

Número total de registros: 15104
Número total de columnas: 45

--- Tipos de datos finales ---
mod                     float64
sub                      object
nrom                     object
departamento             object
categorias               object
co2abs                   object
co2                      object
ch4                     float64
n2o                     float64
hfc-23                  float64
hfc-32                  float64
hfc-125                 float64
hfc-134a                float64
hfc-143a                float64
hfc-152a                float64
hfc-227ea               float64
hfc-236fa               float64
hfc-245fa               float64
hfc-365mfc              float64
hfc-43-10mee            float64
pfc-14                  float64
pfc-116                 float64
sf6                     float64
co2abseq                 object
co2eq                    object
ch4eq                    object
n2oeq                    object
hfc-23eq                float64
hfc-32eq                float64
hfc-125eq               float64
hfc-134aeq              float64
hfc-143aeq              float64
hfc-152aeq              float64
hfc-227eaeq             float64
hfc-236faeq             float64
hfc-245faeq             float64
hfc-365mfceq            float64
hfc-43-10meeeq          float64
pfc-14eq                float64
pfc-116eq               float64
sf6eq                   float64
abosorciones_totales     object
emisiones_totales        object
emisiones_netas          object
sector_principal         object
dtype: object

--- Vista previa del dataset limpio ---

,mod,sub,nrom,departamento,categorias,co2abs,co2,ch4,n2o,hfc-23,...,hfc-245faeq,hfc-365mfceq,hfc-43-10meeeq,pfc-14eq,pfc-116eq,sf6eq,abosorciones_totales,emisiones_totales,emisiones_netas,sector_principal
0,1.0,b,i,CAUCA,1A5bi - Móvil (componente aviación),NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Energía
1,2.0,NaN,NaN,CORDOBA,2A - Industria de los minerales,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Procesos Industriales
2,1.0,a,NaN,GUAINIA,1C1a - Gasoductos,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Energía
3,1.0,b,NaN,GUAINIA,1C1b - Embarcaciones,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Energía
4,1.0,c,NaN,GUAINIA,1C1c - Otros,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,Energía

---
## 8. Carga y almacenamiento (Load)

El paso final del proceso ETL es el Load (Carga). Guardaremos nuestro DataFrame limpio y transformado en un archivo CSV dentro de la carpeta designada para datos procesados. Esto asegura que no sobrescribamos los datos originales (Raw Data) y dejamos la información lista para consumo de modelos de Machine Learning y dashboards analíticos.

Se creará automáticamente la carpeta `dataset/processed/` en caso de que no exista previamente.

In [76]:
# Definimos la ruta de salida
output_dir = Path("../dataset/processed")
output_file = output_dir / "dataset_limpio.csv"
output_file_excel = output_dir / "dataset_limpio.xlsx"

# Creamos el directorio si no existe (crea también carpetas padre si es necesario)
output_dir.mkdir(parents=True, exist_ok=True)

# Guardamos el dataframe sin el índice para evitar una columna extra indeseada
df_excel = df.copy()

df.to_csv(output_file, index=False)
df_excel.to_excel(output_file_excel, index=False)

print(f"El dataset limpio ha sido guardado exitosamente en: {output_file}")

El dataset limpio ha sido guardado exitosamente en: ..\dataset\processed\dataset_limpio.csv

---
## 9. Resumen del proceso

**Reporte de Limpieza ETL:**

*   **Cantidad inicial de columnas:** Reportado en la etapa 4 (Exploración inicial).
*   **Cantidad final de columnas:** Reportado en la etapa 7 (Verificación final).
*   **Columnas eliminadas:** `CAP`, `CAT`, `SUBNROM`, `NUM`, `REPORTAR`, `NIVEL`, `RUBRO`, `SECTORES`.
*   **Registros duplicados eliminados:** Identificados y depurados en la sección 6 (Limpieza básica).
*   **Estado de los valores nulos:** Se generó un conteo por variable para su posterior tratamiento; no se forzó ninguna imputación automatizada.
*   **Ubicación del archivo exportado:** `dataset/processed/dataset_limpio.csv`

El conjunto de datos ahora cuenta con una estructura validada y limpia, listo para proveer insights valiosos y entrenar modelos confiables.